### ISSUE TITLE
Core  1 panic'ed (StoreProhibited) when saying time

### ISSUE THREAD

**Issue by LenStruttmann** [pschatzmann/arduino-simple-tts#1]
Good day!  I am trying to get your Talking Clock to work.  I'm using platformio with the following platformio.ini file:

<CODE>
[platformio]
description = Audio Example
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 ;https://github.com/platformio/platform-espressif32.git
board =lolin_d32 ; esp32dev
framework = arduino
lib_deps = https://github.com/pschatzmann/arduino-audio-tools
            https://github.com/pschatzmann/arduino-simple-tts
            https://github.com/pschatzmann/arduino-libhelix
            https://github.com/pschatzmann/arduino-audiokit
            Wire
build_flags = -DCORE_DEBUG_LEVEL=5 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Wno-format-extra-args
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
</CODE>

My out stream is to a Pmod I2S2, using this config:

<CODE>
 // start I2S
  Serial.println("starting I2S...");
  auto config = i2s.defaultConfig(RXTX_MODE);
  config.sample_rate = 44100; //sample_rate;
  config.bits_per_sample = 16;
  config.i2s_format = I2S_STD_FORMAT;
  config.is_master = true;
  config.port_no = 0;
  config.pin_ws = 18;
  config.pin_bck = 5;
  config.pin_data = 19;
  config.pin_data_rx = 17;
  config.pin_mck = 0;
  config.use_apll = true;

  i2s.begin(config);
</CODE>

Everything compiled fine, but I got the following panic when trying to run:

<CODE>
[I] TimeToText.h : 23 - say: 23:46
[D] SimpleTTSBase.h : 112 - digits: 0
[D] SimpleTTSBase.h : 113 - format: %0.0f
[D] SimpleTTSBase.h : 117 - number: 14
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
</CODE>

To stop the crashing, I made the following changes to TimeToText.h:

Line 111:
      // addAll(ntt.say(time.minute,0u));
      addAll(ntt.say((int64_t)time.minute));

Line: 123:
      // addAll(ntt.say(time.minute,0u));
      addAll(ntt.say((int64_t)time.minute));

Line 135:
    // addAll(ntt.say(hour,0u));
    addAll(ntt.say((int64_t)hour));

Line 150:
    // addAll(ntt.say(hour,0u));
    addAll(ntt.say((int64_t)hour));

**Comment by pschatzmann** [comment]
Thanks for letting me know. 
I haven't used this for a long time...
