### ISSUE TITLE
Numbers with decimal points.

### ISSUE THREAD

**Issue by ConnalM** [pschatzmann/arduino-simple-tts#2]
Hi,

I've tried several of your examples and they sound so much better than others I have come across. However, what I want to do is get tts to speak a number to three decimal places. I see the example where you convert the number to text (700234.2345 or whatever) but the number to speech example uses an integer. So far I haven't been able to get a non-integer version to work. Am I missing something?

I also have another issue when it comes to integrating your code with mine in a larger project but I need to send the errors I am getting for help with that.

Keep up the great work, though. You are way ahead of everyone else!

Connal

**Comment by pschatzmann** [comment]
For doubles: did you try this [example](https://github.com/pschatzmann/arduino-simple-tts/blob/main/examples/audio-i2s/audio-i2s.ino)?

**Comment by ConnalM** [comment]
No. The fact that is labelled "units to text" and includes "usd" put me off. Should I just change integer to double?

**Comment by ConnalM** [comment]
Hi,

I changed the int to a double and gave it a value of 32.57 in one example and 32.537 in another. In the former, tts read out 32.7000000000000... and in the latter, it read out 32.36999999....

**Comment by ConnalM** [comment]
looks like it is ignoring the first digit after the decimal point and approximating the rest? Just tried 17.294 and got 17.9400000...

**Comment by pschatzmann** [comment]
Did you check the documentation of NumberToText ? There are plenty if different way to pass numbers with decimals or specify the number of digits...

I also committed a correction for the number of digits to address the bug which has been added in the last change.
