### ISSUE TITLE
Typo in NumbersToText.h

### ISSUE THREAD

**Issue by LenStruttmann** [pschatzmann/arduino-simple-tts#3]
There is a type in NumberToText.h:

Line 80:
const char* second[10] = {"",      "TEN",   "TWENTY",  "THIRTY", "FORTY",

...should be:
const char* second[10] = {"",      "TEN",   "TWENTY",  "THIRTY", "FOURTY",

**Comment by pschatzmann** [comment]
No: forty is correct!
https://www.merriam-webster.com/words-at-play/is-it-forty-or-fourty

**Comment by LenStruttmann** [comment]
Ok! I see that you changed AudioDictionary.h to match it. Sorry! 

 -------Original Message-------
 From: Phil Schatzmann ***@***.***>
 To: pschatzmann/arduino-simple-tts
***@***.***>
 Cc: LenStruttmann ***@***.***>, Author
***@***.***>
 Subject: Re: [pschatzmann/arduino-simple-tts] Typo in NumbersToText.h
(Issue #3)
 Sent: 16 Jan '23 19:23

No: forty is correct!
 https://www.merriam-webster.com/words-at-play/is-it-forty-or-fourty 

--
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID:
***@***.***>
