### ISSUE TITLE
Issue with using a VolumeStream in Talking Clock

### ISSUE THREAD

**Issue by LenStruttmann** [pschatzmann/arduino-simple-tts#4]
I had no problem adding a VolumeStream to the example streams-generator-i2s.ino sketch. However, I am having an issue attempting to add a VolumeStream to the Talking Clock example.

What I have done:

Added the following override to TextToSpeech.h:
<code> TextToSpeech(SimpleTTSBase &tts, VolumeStream &sink, AudioDecoder &decoder,
               AudioDictionaryBase &dict) {
    tts.registerCallback(callback, this);
    p_tts = &tts;
    p_dictionary = &dict;
    p_decoder = &decoder;
    p_sink = &sink;
    decodedStream = new audio_tools::EncodedAudioStream(&sink, &decoder);
    begin();
  }
</code>

In my main.cpp I have:
<code>
// MP3 DECODER
MP3DecoderHelix mp3;
AudioDictionary dictionary(ExampleAudioDictionaryValues);

// VOLUME STREAM
VolumeStream volumeTime;

// TIME TO TEXT
TimeToText ttt;
TextToSpeech tts(ttt, volumeTime, mp3, dictionary);

StreamCopy copierTime(i2s, volumeTime);
</code>

In my loop() I then have:
<code>
  volumeTime.setVolume( 1.0 );
  copierTime.copy();
</code>

Everything compiles, but when I run it, there is no audio from my I2S device. I am NOT a C++ expert, so I am probably missing something trivial.  Any ideas?

Thanks!

Len Struttmann

**Comment by pschatzmann** [comment]
You forgot to specify to where the volumeTime should output it's data: Have a look at this example: https://github.com/pschatzmann/arduino-simple-tts/blob/main/examples/audio-i2s/audio-i2s.ino
The StreamCopy does not make any sense...

**Comment by LenStruttmann** [comment]
Excellent!  Obviously, I'm just starting out with using your streams and I got confused. Thank you so much for the prompt reply. - Len

**Comment by LenStruttmann** [comment]
BTW: The example listed does not compile.  Line 7 of all.h still says:

#include "fourty.h"

**Comment by pschatzmann** [comment]
It should compile now again...

**Comment by LenStruttmann** [comment]
Thanks!
